Pacemaker/16-nodes-cluster-experiments.md

Details: https://jts.seagate.com/browse/EOS-15489
Signed-off-by: Andrei Zheregelia <andrei.zheregelia@seagate.com>

EOS-15489: Add report for 16-node pacemaker cluster POC

---

Pacemaker/clone_resource.md
Pacemaker/s3server

Signed-off-by: ajay.paratmandali@seagate.com <ajay.paratmandali@seagate.com>

POC: clone resource for s3server like services

---

Pacemaker/scale-cluster-adding-more-nodes-poc.md

Described steps required to add node to cluster.
Described additional configuration that may be required for that
depending on cluster type and enabled features.
Issue: https://jts.seagate.com/browse/EOS-15666

EOS-15666: Add report for scale cluster POC

---

S3/Bucket-Metadata-Cache/2020.12.-LRU-test-results.md
S3/Bucket-Metadata-Cache/README.md

Signed-off-by: Ivan Tishchenko <ivan.tishchenko@seagate.com>

EOS-15900: Add results of S3 LRU experiment

---

daos-cortx/docs/mpifileutils_setup.md

With reference to https://github.com/hpc/mpifileutils/pull/434, I have added one more command form which is very handy to use with mpirun dcp utility.

Add new command form for mpirun dcp comamnd

---

S3/initial-perf-test-on-R2/README.md
S3/initial-perf-test-on-R2/raw-test-results.md
S3/initial-perf-test-on-R2/s3-perf-test-log-2021-01-27_04-23-09.txt

Signed-off-by: Ivan Tishchenko <ivan.tishchenko@seagate.com>
-----
[View rendered S3/initial-perf-test-on-R2/README.md](https://github.com/t7ko-seagate/cortx-experiments/blob/EOS-16575-initial-perf-test-on-R2/S3/initial-perf-test-on-R2/README.md)
[View rendered S3/initial-perf-test-on-R2/raw-test-results.md](https://github.com/t7ko-seagate/cortx-experiments/blob/EOS-16575-initial-perf-test-on-R2/S3/initial-perf-test-on-R2/raw-test-results.md)

EOS-16575: Results of basic perf test on R2 HW

---

Pacemaker/Pacemaker-2-changelog.md

- Analyzed ClusterLabs changelog documents
- Write down changes that affect LR1, LR2 releases
- Explain which activities are affected by aforementioned changes
Signed-off-by: Andrei Zheregelia <andrei.zheregelia@seagate.com>

EOS-16540: add report for  pacemaker 1.1 vs 2.0 changelog

---

Pacemaker/Corosync_Pacemaker_Setup.md
Stonith/docs/scsi/configure_scsi.md

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>
-----
[View rendered Pacemaker/Corosync_Pacemaker_Setup.md](https://github.com/ajay-paratmandali/cortx-experiments/blob/ha_docs/Pacemaker/Corosync_Pacemaker_Setup.md)
[View rendered Stonith/docs/scsi/configure_scsi.md](https://github.com/ajay-paratmandali/cortx-experiments/blob/ha_docs/Stonith/docs/scsi/configure_scsi.md)

Move ha wiki to experiments and add scsi configuration

---

Pacemaker/network-partition-survive-3rd-party-services/Increase-quorum-votes-to-survive-3rd-parties-services.md

-----
[View rendered Pacemaker/network-partition-survive-3rd-party-services/Increase-quorum-votes-to-survive-3rd-parties-services.md](https://github.com/VijayThakkar132/cortx-experiments/blob/EOS-17214/Pacemaker/network-partition-survive-3rd-party-services/Increase-quorum-votes-to-survive-3rd-parties-services.md)

EOS-17214 Network partition - find a way to survive the partition running third party services

---

Pacemaker/POC_pacemaker_remote_with_STONITH.md

Experiment pacemaker_remote by enabling STONITH configuration on VM
-----
[View rendered Pacemaker/POC_pacemaker_remote_with_STONITH.md](https://github.com/ArchanaLimaye/cortx-experiments/blob/main/Pacemaker/POC_pacemaker_remote_with_STONITH.md)

Changes for POC EOS-16832

---

daos-cortx/README.md
daos-cortx/docs/datamovment_with_s3.md

Added documentation for for daos container object movement from daos node to cortx and vice versa using aws s3 cli.
-----
[View rendered daos-cortx/docs/datamovment_with_s3.md](https://github.com/Seagate/cortx-experiments/blob/rajkumarpatel2602-patch-s3-cli-datamovement/daos-cortx/docs/datamovment_with_s3.md)

Daos container object movement using s3 cli

---

.github/pull_request_template.md

Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>
-----
[View rendered .github/pull_request_template.md](https://github.com/gauravchaudhari02/cortx-experiments/blob/add-template/.github/pull_request_template.md)

Adhoc : Add PR template

---

.whitesource

Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>
This repository needs to be scanned for license compliance
Details are described in this JIRA Ticket -> https://jts.seagate.com/browse/CORTX-28737
-  [X] Coding conventions are followed and code is consistent
Changes are made after discussion with whitesource support team.
Scan will be executed as part of PR process
No impact expected on any other components
https://jts.seagate.com/browse/CORTX-28737
Not Applicable

Update whitesource configuration for license scan

---

.whitesource

Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>
This repository needs to be scanned for license compliance.
It is also scanning for vulnerability.
However my understanding is that this repository is not part of any deliverable. So vulnerability scan needs to be disabled.
https://jts.seagate.com/browse/CORTX-28935
Changes are made after discussion with whitesource support team.
Scan will be executed as part of PR process
https://jts.seagate.com/browse/CORTX-28935
Not applicable

Correct .whitesource to disable vulnerability scan

---

ansible/README.md
ansible/ansible_k8s_setup.yml
ansible/final_setup.yml
ansible/host
ansible/initial_setup.yml
ansible/join_nodes.yml
ansible/masternode_config.yml
ansible/workernode_config.yml

Signed-off-by: Pradeep-B-Thangaraj <pradeep.b.thangaraj@seagate.com>
- Kubernetes cluster setup using ansible (*Done as a part of ansible POC - JIRA ID - CH-204*)
-  [x] Coding conventions are followed and code is consistent

CH-204 - Kubernetes cluster setup using ansible

---

logrotation/test/py-utils/python_requirements.txt

Upgrade aiohttp to 3.8.1

---

HA/support-bundle-size-poc/requirements.txt

Upgrade urllib3 to 1.26.9

---

logrotation/test/py-utils/python_requirements.txt

Upgrade PyYAML to 6.0

---

logrotation/test/py-utils/python_requirements.txt

Upgrade cryptography to 3.4.8

---

logrotation/test/py-utils/python_requirements.txt

- Resolve whitesource security scans

Upgrade paramiko to 2.11.0
